### PR TITLE
WIP: Use go modules for building and version controlling

### LINKED ISSUE #47: Add go.mod
Hi, 

Awesome project, would love to contribute, but, can you vendor the dependencies you are using?
Trying to get master of all dependencies and building fails with: 

```
../../../../../barista.run/pango/icons/fontawesome/fontawesome.go:68:8: undefined: yaml.NewDecoder
# barista.run/pango/icons/typicons
../../../../../barista.run/pango/icons/typicons/typicons.go:53:8: undefined: yaml.NewDecoder
```

### PR DESCRIPTION
**Pull request by elemir**
fixes #47

### CODE REVIEW

**Comment by elemir** [comment]
@googlebot I signed it!

**Comment by soumya92** [comment]
Hey, thanks for the pull request! Glad to see you taking this on. I noticed the title is WIP, probably as you work through whatever the CI system needs, so I'll hold off on reviewing it.

But if you need pointers to anything, feel free to post questions/comments here, and just update the title once this is ready for review.

Thanks!

**Comment by elemir** [comment]
@soumya92, hi!

Now I finished adopting project to go modules, but I interested in your idea of autoupdating go.mod when test passed. I see some alternatives:
* Using github api for creating special commit with go.mod updates directly on master. 
* Using precommit hook with go.mod updating

**Comment by soumya92** [comment]
Looks great! I see that we're also on a new version of dbus now. (and the API is nicer).

My plan for automation was to just push a new git commit before every release that updates the go.mod/go.sum files. I might switch the release frequency to weekly if that generates too many commits, or I might need to create a second branch to push releases/updates weekly while retaining the daily tests for the APIs and icon fonts. but that's something I can look at over the next few weeks.

**Pull request merged**
