### PR TITLE
WIP: MPD Module

### PR DESCRIPTION
**Pull request by shibumi**
Hello,
I would like to provide MPD module for barista. For this I want to use: github.com/fhs/gompd
My go is still a little bit bumpy, so I hope you can give me some good tips.

The basic functionality of my module should be:
- [ ]  Show the current state of MPD
- [ ]  Show the current song played in MPD if `state == play`

Additional functionality can be:
- [ ]  Stop current song on mouse click / Start current song on mouse click
- [ ]  Additional buttons for last/next song
- [ ]  Displaying additional information (bitrate, etc)
- [ ] More ideas?

### CODE REVIEW

**Comment by shibumi** [comment]
I signed it!

**Comment by soumya92** [comment]
Is using MPRIS with mpd simple enough? Some other players have add-ins that enable MPRIS which will automatically work with the current media module.

Otherwise this is a good start. If possible let's try to share at least the data structures between both modules. Factoring out a common interface and having mpd + mpris be two different implementations might be even better, but it's a larger undertaking so I'm fine with deferring that.

**Comment by shibumi** [comment]
MPD has no native MPRIS support. There are several MPRIS plugins for MPD, but installing a MPRIS plugin for MPD is too much overhead in my opinion. A MPD module should be doable and the go implemention for mpd is good documented and easy to use: https://github.com/fhs/gompd

**Comment by shibumi** [comment]
I have marked this PR as "work in progress"

**Comment by shibumi** [comment]
Hi @soumya92 I would be still interested in working on this, but I didn't had time over the last couple of months + had some problems understanding your API. I think I will just give it another chance when I have more free time for it and will re-open the PR or open a new one then I have something that is fully functional :)

**Comment by soumya92** [comment]
Ahh, Sorry, I did not read the docs carefully enough :sweat_smile: 

When I changed the default branch to be `main` instead, that caused all PRs against the `master` branch to be unusuable. Oops. You'll need to rebase and re-open.

**Comment by shibumi** [comment]
@soumya92 no problem, my solution wasn't usable. I actually plan to restart from scratch, because I increased my go skills over the last year and would make some stuff different nowadays.

**Pull request closed without merging**
